version: "3"
services:
  tad:
    image: postgres:9.6
    container_name: "postgres"
    environment:
      - POSTGRES_DB=unimed
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
      - "./sql/Formulario.sql:/docker-entrypoint-initdb.d/Formulario.sql"
      - "./sql/Estados.sql:/docker-entrypoint-initdb.d/Estados.sql"
      - "./sql/Cidades.sql:/docker-entrypoint-initdb.d/Cidades.sql"
      
    ports:
      - 5432:5432
